import Config

# # Note we also include the path to a cache manifest
# # containing the digested version of static files. This
# # manifest is generated by the `mix assets.deploy` task,
# # which you should run after static files are built and
# # before starting your production server.
# config :kiosk_example, KioskExampleWeb.Endpoint,
#   cache_static_manifest: "priv/static/cache_manifest.json"
# 
# # Configures Swoosh API Client
# config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: KioskExample.Finch
# 
# # Disable Swoosh Local Memory Storage
# config :swoosh, local: false
# 
# # Do not print debug messages in production
# config :logger, level: :info
# 
# # Runtime production configuration, including reading
# # of environment variables, is done on config/runtime.exs.


################ clauds version ######

import Config

# Configure the endpoint for production
  
config :kiosk_example, KioskExampleWeb.Endpoint,
  # Always start the server in production (for Nerves kiosk)
  server: true,
  # Bind to all interfaces so the kiosk can be accessed
  http: [ip: {0, 0, 0, 0}, port: 80],
  check_origin: false,
  # Disable development features
  code_reloader: false,
  debug_errors: false,
  # You'll need a proper secret key base for production
  secret_key_base: "ZvHStzpTs7SBpWMQ9zD7z7MrJxy7s3d/i/rA54AaoSJyMC/8LouFKdkmRNu2C+y4"

# Disable dev routes
config :kiosk_example, dev_routes: false

# Configure logging for embedded device
config :logger, :console, 
  format: "[$level] $message\n",
  level: :info

# Disable expensive runtime checks
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client
config :swoosh, :api_client, false

# Remove HEEx debug annotations
config :kiosk_example, KioskExampleWeb.Endpoint,
  debug_heex_annotations: false,
  enable_expensive_runtime_checks: false


